---
- name: parse ignition file
  parse_ignition:
    ign_file_contents: "{{ openshift_bootkube_ign_contents }}"
  register: l_parse_ignition_boot_kube_res

- import_tasks: create_files_from_ignition.yml
  vars:
    l_parse_ignition_dict: "{{ l_parse_ignition_boot_kube_res }}"
