---
- name: get worker ignition file
  command: >
    curl -k {{ openshift_bootstrap_endpoint }}
  register: l_worker_bootstrap
  when: openshift_bootstrap_endpoint is defined

- set_fact:
    ign_contents: "{{ l_worker_bootstrap.stdout }}"
  when: openshift_bootstrap_endpoint is defined

- set_fact:
    ign_contents: "{{ lookup('file', openshift_ignition_file_path) }}"
  when: openshift_ignition_file_path is defined

- debug:
    var: ign_contents

- name: parse ignition file
  parse_ignition:
    ign_file_contents: "{{ ign_contents }}"
  register: l_parse_ignition_res


- import_tasks: create_files_from_ignition.yml
  vars:
    l_parse_ignition_dict: "{{ l_parse_ignition_res }}"
