---
- name: Create all the directories we will need
  command: "mkdir -p {{ item }}"
  with_items: "{{ l_parse_ignition_dict.dir_list }}"

- name: create files from ignition contents
  copy:
    content: "{{ item.value.contents }}"
    dest: "{{ item.key }}"
    mode: "{{ l_file_mode }}"
    # owner and group will accept uid/gid respectively.
    owner: "{{ item.value['uid'] | default(omit) }}"
    group: "{{ item.value['gid'] | default(omit) }}"
  with_dict: "{{ l_parse_ignition_dict.files_dict }}"
  vars:
    l_mode_prepend: "{{ '0' if (item.value.mode | length < 4) else '' }}"
    l_file_mode: "{{ l_mode_prepend ~ item.value.mode }}"
