---
- name: Additional node config
  hosts: oo_nodes_to_config
  vars:
    openshift_node_master_api_url: "{{ hostvars[groups.oo_first_master.0].openshift.master.api_url }}"
  roles:
  - role: openshift_facts
  - role: openshift_etcd_facts
  - role: openshift_etcd_client_certificates
    etcd_cert_prefix: flannel.etcd-
    etcd_ca_host: "{{ groups.oo_etcd_to_config.0 }}"
    etcd_cert_subdir: "openshift-node-{{ openshift.common.hostname }}"
    etcd_cert_config_dir: "{{ openshift.common.config_base }}/node"
  - role: flannel
    etcd_urls: "{{ hostvars[groups.oo_first_master.0].openshift.master.etcd_urls }}"
    embedded_etcd: "{{ hostvars[groups.oo_first_master.0].openshift.master.embedded_etcd }}"
    when: openshift_use_flannel | default(false) | bool
  - role: calico
    when: openshift_use_calico | default(false) | bool
  - role: nuage_node
    when: openshift_use_nuage | default(false) | bool
  - role: contiv
    contiv_role: netplugin
    when: openshift_use_contiv | default(false) | bool
  - role: nickhammond.logrotate
  - role: openshift_manage_node
    openshift_master_host: "{{ groups.oo_first_master.0 }}"
    when: not openshift_node_bootstrap | default(False)
  tasks:
  - name: Create group for deployment type
    group_by: key=oo_nodes_deployment_type_{{ openshift.common.deployment_type }}
    changed_when: False
