---
- name: Ensure that all non-node hosts are accessible
  hosts: oo_masters_to_config:oo_etcd_to_config:oo_lb_to_config:oo_nfs_to_config
  any_errors_fatal: true
  tasks:

- name: Initialize basic host facts
  # l_init_fact_hosts is passed in via play during control-plane-only
  # upgrades and scale-up plays; otherwise oo_all_hosts is used.
  hosts: "{{ l_init_fact_hosts | default('oo_all_hosts') }}"
  roles:
  - role: openshift_facts
  tasks:
  # TODO: Should this role be refactored into health_checks??
  - name: Run openshift_sanitize_inventory to set variables
    import_role:
      name: openshift_sanitize_inventory

  - name: Detect OS Variant from /etc/os-release
    fail:
      msg: Atomic Host installations are no longer supported
    when: lookup('ini', 'VARIANT_ID type=properties file=/etc/os-release') == 'atomic.host'

  # TODO(michaelgugino) remove this line once CI is updated.
  - name: set openshift_deployment_type if unset
    set_fact:
      openshift_deployment_type: "{{ deployment_type }}"
      openshift_is_atomic: False
    when:
    - openshift_deployment_type is undefined
    - deployment_type is defined

- name: Read in openshift-install
  hosts: masters[0]
  tasks:
  - slurp:
      src: "{{ openshift_install_config_path }}"
    register: openshift_install_config_reg
    delegate_to: localhost
    run_once: True
  - set_fact:
      openshift_install_config: "{{ openshift_install_config_reg['content'] | b64decode | from_yaml }}"

# We might need to access these values on each host later.
- name: set_fact openshift_install_config across all nodes
  hosts: "{{ l_init_fact_hosts | default('nodes') }}"
  tasks:
  - set_fact:
      openshift_install_config: "{{ hostvars[groups['masters'][0]].openshift_install_config }}"
